//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Nuovo_flight_simulator : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Thrust
        {
            get
            {
                return SteamVR_Actions.nuovo_flight_simulator_Thrust;
            }
        }
        
        public virtual SteamVR_Action_Boolean Brake
        {
            get
            {
                return SteamVR_Actions.nuovo_flight_simulator_Brake;
            }
        }
        
        public virtual SteamVR_Action_Boolean Shift
        {
            get
            {
                return SteamVR_Actions.nuovo_flight_simulator_Shift;
            }
        }
        
        public virtual SteamVR_Action_Boolean ThrustControlSensitivity
        {
            get
            {
                return SteamVR_Actions.nuovo_flight_simulator_ThrustControlSensitivity;
            }
        }
        
        public virtual SteamVR_Action_Boolean Gears
        {
            get
            {
                return SteamVR_Actions.nuovo_flight_simulator_Gears;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwitchCamera
        {
            get
            {
                return SteamVR_Actions.nuovo_flight_simulator_SwitchCamera;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Driving
        {
            get
            {
                return SteamVR_Actions.nuovo_flight_simulator_Driving;
            }
        }
    }
}
